-- Extend the existing GSS schema without dropping or rewriting existing rows.
-- Existing public content is retained and the original hardcoded public content
-- is copied with title-based idempotency checks.

alter table public.services
  add column if not exists tag text not null default '',
  add column if not exists icon_key text not null default 'shield-check',
  add column if not exists sort_order integer not null default 0;

alter table public.events
  add column if not exists event_type text not null default 'COMMUNITY',
  add column if not exists display_status text not null default '',
  add column if not exists sort_order integer not null default 0;

alter table public.notifications
  add column if not exists notification_type text not null default 'COMPANY UPDATE',
  add column if not exists display_date text not null default '',
  add column if not exists sort_order integer not null default 0;

alter table public.complaints
  add column if not exists status text not null default 'pending',
  add column if not exists resolved_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.complaints'::regclass
      and conname = 'complaints_status_check'
  ) then
    alter table public.complaints
      add constraint complaints_status_check check (status in ('pending', 'resolved'));
  end if;
end $$;

alter table public.sites
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.guards (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null default '',
  email text,
  designation text not null default 'Security Guard',
  status text not null default 'active' check (status in ('active', 'inactive', 'on_leave')),
  joining_date date,
  site_id bigint references public.sites(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  service text not null default '',
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  role text not null default '',
  message text not null default '',
  status text not null default 'new' check (status in ('new', 'reviewing', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guards_site_id_idx on public.guards(site_id);
create index if not exists guards_status_idx on public.guards(status);
create index if not exists complaints_created_at_idx on public.complaints(created_at desc);
create index if not exists contact_submissions_created_at_idx on public.contact_submissions(created_at desc);
create index if not exists job_applications_created_at_idx on public.job_applications(created_at desc);

-- Seed the five formerly hardcoded service cards without deleting or replacing
-- any existing service. Rerunning this block will not create duplicate titles.
insert into public.services (title, description, tag, icon_key, sort_order)
select seed.title, seed.description, seed.tag, seed.icon_key, seed.sort_order
from (values
  ('Security Guard / ASO', 'Professional security guard deployment and Assistant Security Officer services for workplaces, facilities and events.', 'PHYSICAL SECURITY', 'shield-check', 1),
  ('VPAT', 'Assessment service information and scope can be tailored to your organization''s requirements.', 'ASSESSMENT SERVICES', 'shield', 2),
  ('Web Security', 'Authorized website security reviews, vulnerability assessment and practical remediation guidance.', 'DIGITAL DEFENCE', 'globe', 3),
  ('Web Designing', 'Responsive business websites with clear information architecture, accessible design and polished user experiences.', 'DIGITAL PRESENCE', 'code', 4),
  ('Cyber Awareness', 'Cyber safety programs, awareness sessions and workshops for students, teams and communities.', 'EDUCATION & OUTREACH', 'graduation-cap', 5)
) as seed(title, description, tag, icon_key, sort_order)
where not exists (
  select 1 from public.services existing where existing.title = seed.title
);

insert into public.events (title, description, event_type, display_status, sort_order)
select seed.title, seed.description, seed.event_type, seed.display_status, seed.sort_order
from (values
  ('Cyber Safety Awareness Session', 'Practical guidance on phishing, passwords, privacy and safer digital habits.', 'AWARENESS PROGRAM', 'Event details will be announced shortly.', 1),
  ('Digital Security Workshop', 'An introductory session on everyday security practices and responsible technology use.', 'COMMUNITY', 'Registration is not open yet.', 2)
) as seed(title, description, event_type, display_status, sort_order)
where not exists (
  select 1 from public.events existing where existing.title = seed.title
);

insert into public.notifications (title, message, notification_type, display_date, sort_order)
select seed.title, seed.message, seed.notification_type, seed.display_date, seed.sort_order
from (values
  ('Welcome to Golconda Security Services', 'Our website is being prepared. Follow our official channels for announcements and upcoming programs.', 'COMPANY UPDATE', 'Latest update', 1),
  ('Pause before you click', 'Verify unexpected links and requests before sharing passwords, OTPs or sensitive information.', 'CYBER AWARENESS', 'Safety reminder', 2)
) as seed(title, message, notification_type, display_date, sort_order)
where not exists (
  select 1 from public.notifications existing where existing.title = seed.title
);

-- Keep all writes behind the existing SECURITY DEFINER admin predicate. Public
-- users can read only the three public content collections and cannot insert
-- complaint/contact/application rows directly; those arrive through the API.
alter table public.services enable row level security;
alter table public.events enable row level security;
alter table public.notifications enable row level security;
alter table public.sites enable row level security;
alter table public.guards enable row level security;
alter table public.complaints enable row level security;
alter table public.contact_submissions enable row level security;
alter table public.job_applications enable row level security;
alter table public.profile_docs enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public can submit complaints" on public.complaints;
drop policy if exists "Admins manage complaints" on public.complaints;
create policy "Admins manage complaints" on public.complaints
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read services" on public.services;
drop policy if exists "Admins can insert services" on public.services;
drop policy if exists "Admins can update services" on public.services;
drop policy if exists "Admins can delete services" on public.services;
create policy "Public can read services" on public.services
  for select to anon, authenticated using (true);
create policy "Admins manage services" on public.services
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read events" on public.events;
drop policy if exists "Admins can insert events" on public.events;
drop policy if exists "Admins can update events" on public.events;
drop policy if exists "Admins can delete events" on public.events;
create policy "Public can read events" on public.events
  for select to anon, authenticated using (true);
create policy "Admins manage events" on public.events
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read notifications" on public.notifications;
drop policy if exists "Admins can insert notifications" on public.notifications;
drop policy if exists "Admins can update notifications" on public.notifications;
drop policy if exists "Admins can delete notifications" on public.notifications;
create policy "Public can read notifications" on public.notifications
  for select to anon, authenticated using (true);
create policy "Admins manage notifications" on public.notifications
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins manage sites" on public.sites;
create policy "Admins manage sites" on public.sites
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins manage profile docs" on public.profile_docs;
create policy "Admins manage profile docs" on public.profile_docs
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins manage guards" on public.guards;
create policy "Admins manage guards" on public.guards
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins manage contact submissions" on public.contact_submissions;
create policy "Admins manage contact submissions" on public.contact_submissions
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins manage job applications" on public.job_applications;
create policy "Admins manage job applications" on public.job_applications
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read own admin record" on public.admin_users;
create policy "Admins can read own admin record" on public.admin_users
  for select to authenticated using (user_id = (select auth.uid()));

revoke all on table public.services, public.events, public.notifications,
  public.sites, public.guards, public.complaints, public.contact_submissions,
  public.job_applications, public.profile_docs, public.admin_users
  from anon, authenticated, public;

grant select on table public.services, public.events, public.notifications to anon, authenticated;
grant select, insert, update, delete on table public.services, public.events,
  public.notifications, public.sites, public.guards, public.complaints,
  public.contact_submissions, public.job_applications, public.profile_docs to authenticated;
grant select on table public.admin_users to authenticated;

grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_admin() to authenticated;
